[mypy]
python_version = 3.12
mypy_path = .
files = tests/application_client, tests/standalone, tests/swap
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
pretty = True
exclude = (?x)(
    venv |
    _helper_tool\.py |
    helper_tool_clone_dependencies\.py |
    helper_tool_build_dependencies\.py
  )

[mypy-hid.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-ledgered.*]
ignore_missing_imports = True

[mypy-ragger.*]
ignore_missing_imports = True

[mypy-base58.*]
ignore_missing_imports = True

[mypy-bech32.*]
ignore_missing_imports = True

[mypy-bech32m.*]
ignore_missing_imports = True

[mypy-bip_utils.*]
ignore_missing_imports = True

[mypy-cbor2.*]
ignore_missing_imports = True

[mypy-ecdsa.*]
ignore_missing_imports = True

[mypy-ledger_app_clients.*]
ignore_missing_imports = True
