# SPDX-FileCopyrightText: 2025-2026 Vacuumlabs
# SPDX-License-Identifier: Apache-2.0

import inspect
import re
import shutil
import subprocess
import sys
import tempfile
import types
from pathlib import Path

from tests.unit.generators.paths import (
    REPO_ROOT,
)


def format_display_name(prefix: str, test_name: str) -> str:
    """Format a display name for a test case."""
    cleaned = test_name.replace("-", "_").replace(" ", "_")
    cleaned = "_".join(part for part in cleaned.split("_") if part)
    return f"[{prefix}] {cleaned}"


def read_file_safe(file_path: Path) -> str:
    """Read file with proper error handling. Exits immediately on error."""
    if not file_path.exists():
        print(f"ERROR: Input file not found: {file_path}")
        sys.exit(1)

    try:
        return file_path.read_text(encoding="utf-8")
    except PermissionError as exc:
        print(f"ERROR: Permission denied reading {file_path}: {exc}")
        sys.exit(1)
    except UnicodeDecodeError as exc:
        print(f"ERROR: File encoding error in {file_path}: {exc}")
        sys.exit(1)
    except OSError as exc:
        print(f"ERROR: Failed to read file {file_path}: {exc}")
        sys.exit(1)
    except Exception as exc:
        print(f"ERROR: Unexpected error reading {file_path}: {exc}")
        sys.exit(1)


def write_file_safe(file_path: Path, content: str) -> None:
    """
    Write file with proper error handling. Exits immediately on error.
    Uses a temporary file and atomic rename to prevent data corruption.
    """
    try:
        # Create parent directories if needed
        file_path.parent.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        print(f"ERROR: Failed to create directory {file_path.parent}: {exc}")
        sys.exit(1)

    temp_file_path = None
    try:
        # Create a temporary file in the same directory
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            delete=False,  # Don't delete immediately
            dir=file_path.parent,
            prefix=f".{file_path.name}.",  # Prefix with dot for hidden file
        ) as tmp_file:
            tmp_file.write(content)
            temp_file_path = Path(tmp_file.name)

        # tempfile.NamedTemporaryFile creates files with 0600; explicitly set g+rw
        temp_file_path.chmod(0o660)

        # Atomically rename the temporary file to the final destination
        temp_file_path.rename(file_path)

    except PermissionError as exc:
        print(f"ERROR: Permission denied writing to {file_path}: {exc}")
        sys.exit(1)
    except OSError as exc:
        print(f"ERROR: Failed to write file {file_path}: {exc}")
        sys.exit(1)
    except Exception as exc:
        print(f"ERROR: Unexpected error writing {file_path}: {exc}")
        sys.exit(1)
    finally:
        # Clean up temporary file if it still exists (e.g., if rename failed)
        if temp_file_path and temp_file_path.exists():
            try:
                temp_file_path.unlink()
            except OSError as exc:
                print(
                    f"WARNING: Failed to clean up temporary file {temp_file_path}: {exc}"
                )


def write_generated_c_file(file_path: Path, content: str) -> None:
    """Write a generated C/H file with standard SPDX and provenance headers."""
    caller_file = "tests/unit/generators/generate_unit_tests_from_ragger.py"
    try:
        # stack[1] is the caller of write_generated_c_file
        caller_frame = inspect.stack()[1]
        caller_path = Path(caller_frame.filename).resolve()
        # Make path relative to REPO_ROOT if possible
        try:
            caller_file = caller_path.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            caller_file = caller_path.name
    except Exception:
        pass

    header = (
        "// SPDX-FileCopyrightText: 2025-2026 Vacuumlabs\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "\n"
        f"// Generated by: {caller_file}\n"
        "\n"
    )

    full_content = header + content
    clang_format_path = shutil.which("clang-format-14")
    if clang_format_path is not None:
        try:
            clang_format_result = subprocess.run(
                [clang_format_path, f"--assume-filename={file_path.name}"],
                input=full_content,
                text=True,
                capture_output=True,
                check=True,
            )
            full_content = clang_format_result.stdout
        except subprocess.CalledProcessError as exc:
            print(
                "ERROR: clang-format-14 failed while formatting generated file "
                f"{file_path}: {exc.stderr.strip()}"
            )
            sys.exit(1)
    if not full_content.endswith("\n"):
        full_content += "\n"
    write_file_safe(file_path, full_content)


def sanitize_c_identifier(
    name: str, uppercase: bool = True, handle_leading_digit: bool = False
) -> str:
    """
    Convert arbitrary string to valid C identifier.

    Replaces non-alphanumeric characters with underscores, collapses consecutive
    underscores, and optionally converts to uppercase.

    Args:
        name: Input string to sanitize
        uppercase: If True, convert to UPPER_SNAKE_CASE; if False, use lower_snake_case
        handle_leading_digit: If True, prefix with "num_" if name starts with digit

    Returns:
        Valid C identifier string

    Examples:
        >>> sanitize_c_identifier("path too short")
        'PATH_TOO_SHORT'
        >>> sanitize_c_identifier("base key/key with wrong path")
        'BASE_KEY_KEY_WITH_WRONG_PATH'
        >>> sanitize_c_identifier("test-case #1", uppercase=False)
        'test_case_1'
        >>> sanitize_c_identifier("123_test", handle_leading_digit=True)
        'NUM_123_TEST'
    """
    # Replace non-alphanumeric characters with underscores
    sanitized = "".join(c if c.isalnum() else "_" for c in name)

    # Collapse multiple consecutive underscores
    sanitized = re.sub(r"_+", "_", sanitized)

    # Strip leading/trailing underscores
    sanitized = sanitized.strip("_")

    # Handle leading digit if requested
    if handle_leading_digit and sanitized and sanitized[0].isdigit():
        sanitized = f"num_{sanitized}"

    # Handle empty string case
    if not sanitized:
        sanitized = "unnamed"

    # Convert case
    return sanitized.upper() if uppercase else sanitized.lower()


def warning_expr_from_test_case(test_case: object) -> str:
    """Return a C expression for the expected_warning_bits field.

    Produces a bit-OR expression suitable for embedding directly in a C
    struct initialiser, e.g.::

        ((warning_bits_t)1 << WARNING_FOO) | ((warning_bits_t)1 << WARNING_BAR)

    Returns ``"0"`` when no warnings are expected.
    """
    expected_warnings = getattr(test_case, "expected_warnings", [])
    if expected_warnings:
        return " | ".join(
            f"((warning_bits_t)1 << {bit.name})" for bit in expected_warnings
        )
    return "0"


def bool_to_c(value: bool) -> str:
    """Convert a Python bool to a C bool literal."""
    return "true" if value else "false"


def hex_string_to_c_string_lines(
    hex_str: str,
    *,
    indent: int = 4,
    chunk_size: int = 64,
    append_comma: bool = False,
) -> list[str]:
    """Split a hex string into indented C string-literal lines."""
    lines = []
    for index in range(0, len(hex_str), chunk_size):
        segment = hex_str[index : index + chunk_size]
        lines.append(" " * indent + f'"{segment}"')
    if append_comma and lines:
        lines[-1] = lines[-1] + ","
    return lines


def extract_apdu_payload(apdu: bytes) -> bytes:
    """
    Extract payload from APDU command.

    APDU format: [CLA: 1][INS: 1][P1: 1][P2: 1][LC: 1][DATA: LC bytes]

    Args:
        apdu: Complete APDU command with 5-byte header

    Returns:
        Payload bytes (DATA portion only, starting at offset 5)

    Raises:
        ValueError: If APDU is too short or payload length mismatch

    Examples:
        >>> apdu = b'\\x00\\x01\\x02\\x03\\x05\\xAA\\xBB\\xCC\\xDD\\xEE'
        >>> extract_apdu_payload(apdu)
        b'\\xAA\\xBB\\xCC\\xDD\\xEE'
    """
    MIN_HEADER_LENGTH = 5

    if len(apdu) < MIN_HEADER_LENGTH:
        raise ValueError(
            f"APDU command too short: {len(apdu)} bytes "
            f"(expected at least {MIN_HEADER_LENGTH})"
        )

    lc = apdu[4]
    payload_start = 5

    payload_length = lc

    payload_end = payload_start + payload_length
    payload_bytes = apdu[payload_start:payload_end]

    if len(payload_bytes) != payload_length:
        raise ValueError(
            f"Payload length mismatch: Lc field says {payload_length} bytes, "
            f"but got {len(payload_bytes)} bytes"
        )

    return payload_bytes


def format_bytes_as_c_array(
    data: bytes, name: str, bytes_per_line: int = 8, return_as_list: bool = False
) -> str | list[str]:
    """
    Generate C code for a byte array declaration.

    Args:
        data: Byte data to format
        name: C identifier for the array
        bytes_per_line: Number of bytes per line for readability (default: 16)
        return_as_list: If True, return list of lines; if False, return single string

    Returns:
        C code as string or list of strings

    Examples:
        >>> format_bytes_as_c_array(b'\\xAA\\xBB\\xCC', "TEST_DATA")
        'static const uint8_t TEST_DATA[] = {\\n    0xAA, 0xBB, 0xCC,\\n};'
        >>> format_bytes_as_c_array(b'\\xAA\\xBB\\xCC', "TEST_DATA", return_as_list=True)
        ['static const uint8_t TEST_DATA[] = {', '    0xAA, 0xBB, 0xCC,', '};']
        >>> format_bytes_as_c_array(b'', "EMPTY_DATA")
        'static const uint8_t EMPTY_DATA[1] = { 0x00 };'
    """
    lines = []

    if len(data) == 0:
        # Empty payloads: use explicit size [1] with dummy byte for C99 compatibility
        # Callers must explicitly pass 0 as length, not sizeof()
        declaration_line = f"static const uint8_t {name}[1] = {{ 0x00 }};"
        if len(declaration_line) > 88:
            lines.append("static const uint8_t")
            lines.append(f"    {name}[1] = {{ 0x00 }};")
        else:
            lines.append(declaration_line)
    else:
        declaration_line = f"static const uint8_t {name}[] = {{"
        if len(declaration_line) > 88:
            lines.append("static const uint8_t")
            lines.append(f"    {name}[] = {{")
        else:
            lines.append(declaration_line)
        for i in range(0, len(data), bytes_per_line):
            chunk = data[i : i + bytes_per_line]
            hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
            lines.append(f"    {hex_bytes},")
        lines.append("};")

    if return_as_list:
        return lines
    return "\n".join(lines)


ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
ALPHABET_INDEX = {char: index for index, char in enumerate(ALPHABET)}


def _ensure_base58_module() -> None:
    if "base58" in sys.modules:
        return

    def b58encode(data: bytes) -> bytes:
        if not data:
            return b""

        zero_prefix = 0
        for byte in data:
            if byte == 0:
                zero_prefix += 1
            else:
                break
        num = int.from_bytes(data, "big")
        encoded_bytes = bytearray()
        while num > 0:
            num, remainder = divmod(num, 58)
            encoded_bytes.append(ord(ALPHABET[remainder]))
        encoded_bytes.reverse()
        result = bytearray(b"1" * zero_prefix)
        if encoded_bytes:
            result.extend(encoded_bytes)
        elif zero_prefix == 0:
            result.extend(b"1")
        return bytes(result)

    def b58decode(value: bytes | str) -> bytes:
        if isinstance(value, bytes):
            value = value.decode("ascii")
        if value == "":
            return b""
        num = 0
        for char in value:
            num = num * 58 + ALPHABET_INDEX[char]
        decoded = num.to_bytes((num.bit_length() + 7) // 8, "big") if num > 0 else b""
        zero_prefix = len(value) - len(value.lstrip("1"))
        return b"\x00" * zero_prefix + decoded

    module = types.ModuleType("base58")
    module.b58encode = b58encode
    module.b58decode = b58decode
    sys.modules["base58"] = module


def resolve_mnemonic() -> str:
    """Return the test mnemonic to use for key derivation.

    Checks ``ragger_configuration.OPTIONAL.CUSTOM_SEED`` first; falls back to
    the standard ``abandon … about`` mnemonic used across the test suite.
    """
    default_mnemonic = (
        "abandon abandon abandon abandon abandon abandon "
        "abandon abandon abandon abandon abandon about"
    )
    try:
        from ragger.conftest import configuration as ragger_configuration  # type: ignore
    except ImportError:
        return default_mnemonic

    if ragger_configuration is not None:
        optional_seed = getattr(ragger_configuration.OPTIONAL, "CUSTOM_SEED", "")
        if optional_seed:
            return optional_seed

    return default_mnemonic


def extract_brace_delimited_entries(
    body: str,
    start_pattern: "re.Pattern[str] | None" = None,
) -> list[str]:
    """Extract top-level brace-delimited C struct entries from *body*.

    Each entry starts where *start_pattern* matches (default: any ``{``)
    and ends at the matching closing brace (depth-tracking).  Trailing
    whitespace, commas, and newlines following the closing brace are
    consumed so that the returned strings are ready to hand to a subsequent
    regex.

    Raises ``ValueError`` on unbalanced braces.
    """
    entries: list[str] = []
    search_pos = 0
    while True:
        if start_pattern is None:
            open_pos = body.find("{", search_pos)
            if open_pos == -1:
                break
            match_start = open_pos
        else:
            m = start_pattern.search(body, search_pos)
            if not m:
                break
            match_start = m.start()
            open_pos = body.find("{", match_start)
            if open_pos == -1:
                break

        depth = 0
        idx = open_pos
        end_idx = -1
        while idx < len(body):
            char = body[idx]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    end_idx = idx + 1
                    break
            idx += 1
        if end_idx == -1:
            raise ValueError("Unbalanced braces while parsing entries")
        # Consume trailing whitespace/comma/newline after the closing brace
        while end_idx < len(body) and body[end_idx] in " \t\r\n,":
            end_idx += 1
        entries.append(body[match_start:end_idx])
        search_pos = end_idx
    return entries


def _find_matching_closing_brace(content: str, open_brace_index: int) -> int:
    """Return the index of the matching closing brace for *open_brace_index*."""
    if open_brace_index < 0 or open_brace_index >= len(content):
        raise ValueError("Opening brace index out of bounds")
    if content[open_brace_index] != "{":
        raise ValueError("Opening brace not found at the provided index")

    depth = 0
    index = open_brace_index
    while index < len(content):
        char = content[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    raise ValueError("Unbalanced braces while parsing declaration body")


def extract_static_uint8_array_bodies(content: str) -> dict[str, str]:
    """Return ``static const uint8_t`` array initializers keyed by array name."""
    declaration_pattern = re.compile(
        r"static\s+const\s+uint8_t\s+([A-Z0-9_]+)\s*\[\s*(?:\d+)?\s*\]\s*=\s*\{",
        flags=re.DOTALL,
    )

    arrays: dict[str, str] = {}
    for match in declaration_pattern.finditer(content):
        array_name = match.group(1)
        opening_brace_index = content.find("{", match.start())
        if opening_brace_index == -1:
            raise ValueError(
                f"Missing opening brace for array declaration {array_name}"
            )
        closing_brace_index = _find_matching_closing_brace(content, opening_brace_index)
        arrays[array_name] = content[opening_brace_index + 1 : closing_brace_index]
    return arrays


def remove_static_uint8_arrays_by_name(content: str, array_names: set[str]) -> str:
    """Remove complete ``static const uint8_t`` array declarations by name."""
    if not array_names:
        return content

    declaration_pattern = re.compile(
        r"static\s+const\s+uint8_t\s+([A-Z0-9_]+)\s*\[\s*(?:\d+)?\s*\]\s*=\s*\{",
        flags=re.DOTALL,
    )

    result_chunks: list[str] = []
    cursor = 0
    for match in declaration_pattern.finditer(content):
        array_name = match.group(1)
        if array_name not in array_names:
            continue

        opening_brace_index = content.find("{", match.start())
        if opening_brace_index == -1:
            raise ValueError(
                f"Missing opening brace for array declaration {array_name}"
            )
        closing_brace_index = _find_matching_closing_brace(content, opening_brace_index)

        declaration_end = closing_brace_index + 1
        while declaration_end < len(content) and content[declaration_end] in " \t":
            declaration_end += 1
        if declaration_end < len(content) and content[declaration_end] == ";":
            declaration_end += 1
        while declaration_end < len(content) and content[declaration_end] in "\r\n":
            declaration_end += 1

        result_chunks.append(content[cursor : match.start()])
        cursor = declaration_end

    result_chunks.append(content[cursor:])
    return "".join(result_chunks)
