/* SPDX-FileCopyrightText: 2026 Vacuumlabs */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include "assert.h"

// Source of truth for these strings is CIP-0005. Keep only prefixes currently used by this app.

// Longest currently used prefix is 15 characters, e.g. "addr_shared_vkh".
#define MAX_BECH32_PREFIX_LENGTH 15

#define BECH32_PREFIX_LENGTH(prefix) (sizeof(prefix) - 1)
#define ASSERT_VALID_BECH32_PREFIX(prefix)                                  \
    STATIC_ASSERT(BECH32_PREFIX_LENGTH(prefix) <= MAX_BECH32_PREFIX_LENGTH, \
                  "Bech32 prefix too long")

// Keys
#define BECH32_PREFIX_KES_VERIFICATION_KEY "kes_vk"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_KES_VERIFICATION_KEY);

// Hashes and fingerprints
#define BECH32_PREFIX_ASSET_FINGERPRINT "asset"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_ASSET_FINGERPRINT);
#define BECH32_PREFIX_POOL_ID "pool"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_POOL_ID);
#define BECH32_PREFIX_SCRIPT_HASH "script"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_SCRIPT_HASH);
#define BECH32_PREFIX_SHARED_ADDRESS_KEY_HASH "addr_shared_vkh"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_SHARED_ADDRESS_KEY_HASH);
#define BECH32_PREFIX_STAKE_KEY_HASH "stake_vkh"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_STAKE_KEY_HASH);
#define BECH32_PREFIX_REQUIRED_SIGNER_HASH "req_signer_vkh"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_REQUIRED_SIGNER_HASH);
#define BECH32_PREFIX_VRF_KEY_HASH "vrf_vkh"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_VRF_KEY_HASH);
#define BECH32_PREFIX_DATUM_HASH "datum"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_DATUM_HASH);
#define BECH32_PREFIX_SCRIPT_DATA_HASH "script_data"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_SCRIPT_DATA_HASH);

// Governance identifiers
#define BECH32_PREFIX_DREP "drep"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_DREP);
#define BECH32_PREFIX_COMMITTEE_COLD "cc_cold"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_COMMITTEE_COLD);
#define BECH32_PREFIX_COMMITTEE_HOT "cc_hot"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_COMMITTEE_HOT);
#define BECH32_PREFIX_GOV_ACTION "gov_action"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_GOV_ACTION);

// Addresses
#define BECH32_PREFIX_ADDRESS "addr"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_ADDRESS);
#define BECH32_PREFIX_TESTNET_ADDRESS "addr_test"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_TESTNET_ADDRESS);
#define BECH32_PREFIX_STAKE_ADDRESS "stake"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_STAKE_ADDRESS);
#define BECH32_PREFIX_TESTNET_STAKE_ADDRESS "stake_test"
ASSERT_VALID_BECH32_PREFIX(BECH32_PREFIX_TESTNET_STAKE_ADDRESS);
