# SPDX-FileCopyrightText: 2025-2026 Vacuumlabs
# SPDX-License-Identifier: Apache-2.0

from enum import IntEnum


class WarningBit(IntEnum):
    # Canonical names and values match `src/securityPolicy/securityWarnings.h`.
    WARNING_BIT_UNUSUAL_KEY_DERIVATION_PATH = 0
    WARNING_BIT_NETWORK_UNUSUAL = 1
    WARNING_BIT_NETWORK_NOT_VERIFIABLE = 2
    WARNING_BIT_PLUTUS_MISSING_COLLATERAL = 3
    WARNING_BIT_PLUTUS_UNKNOWN_COLLATERAL = 4
    WARNING_BIT_COLLATERAL_OUTPUT_WARNING = 5
    WARNING_BIT_PLUTUS_MISSING_SCRIPT_DATA_HASH = 6
    WARNING_BIT_OUTPUT_MISSING_DATUM = 7
    WARNING_BIT_CVOTE_PAYMENT_THIRD_PARTY = 8
    WARNING_BIT_CVOTE_PAYMENT_NONSTANDARD_OWNED = 9
    WARNING_BIT_CVOTE_WITNESS_NOT_FULLY_VERIFIABLE = 10
    WARNING_BIT_POOL_REGISTRATION_NO_OWNERS = 11
    WARNING_BIT_POOL_REGISTRATION_NO_RELAYS = 12
    WARNING_BIT_POOL_REGISTRATION_EMPTY_METADATA_URL = 13
    WARNING_BIT_EMPTY_ANCHOR_URL = 14
    WARNING_BIT_HIGH_FEE = 15
    WARNING_BIT_UNRESTRICTED_SIGNING = 16
